name: Perbarui README.md dengan Daftar Folder

on:
  push:
    paths:
      - '**/*'  # Memicu workflow saat ada perubahan di folder manapun

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositori
        uses: actions/checkout@v2

      - name: Ambil semua folder
        id: get_folders
        run: |
          # Mendapatkan semua folder kecuali .github dan node_modules
          FOLDERS=$(ls -d */ | grep -v '\.github\|node_modules' | sed 's/\/$//')
          echo "folders=$(echo "$FOLDERS" | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Perbarui README.md
        run: |
          # Jika tidak ada folder dalam repositori, keluar
          if [ -z "${{ env.folders }}" ]; then
            echo "Tidak ada folder yang ditemukan di repositori."
            exit 0
          fi

          # Baca template dari template.md
          TEMPLATE_FILE="template.md"
          README_FILE="README.md"

          # Hapus isi file README.md
          > $README_FILE

          # Salin konten template ke file README.md
          cp $T
