name: Update HTML with Folders

on:
  push:
    paths:
      - '**/*'  # Memicu workflow saat ada perubahan di folder manapun
  schedule:
    - cron: '*/5 * * * *'  # Opsional: Menjalankan setiap 5 menit (jika ada perubahan otomatis setiap interval)

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get all folders
        id: get_folders
        run: |
          # Mendapatkan semua folder kecuali .github dan node_modules, lalu menghapus trailing slash
          FOLDERS=$(ls -d */ | grep -v '\.github\|node_modules' | sed 's/\/$//')
          # Simpan folder dengan format dipisahkan spasi (untuk bisa digunakan oleh GitHub Actions)
          echo "folders=$(echo "$FOLDERS" | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Check for changes and update index.html
        run: |
          if [ -z "${{ env.folders }}" ]; then
            echo "No folders found."
            exit 0
          fi

          # Generate folder list for HTML
          FOLDER_LIST=""
          for folder in ${{ env.folders }}; do
            FOLDER_LIST="$FOLDER_LIST<li><a href=\"$folder/\">${folder}</a></li>\n"
          done

          # Append folder list below the FOLDER_LIST_PLACEHOLDER without removing the placeholder
          awk '/<!-- FOLDER_LIST_PLACEHOLDER -->/ { print; print FOLDER_LIST; next }1' FOLDER_LIST="$FOLDER_LIST" index.html > index.html.new
          mv index.html.new index.html

          # Check if index.html has changed
          if git diff --quiet; then
            echo "No changes to index.html. Skipping commit."
            exit 0
          fi

          # If changes exist, commit and push the update
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add index.html
          git commit -m "Update index.html with project folders"
          git push
