name: Update HTML with Folders

on:
  schedule:
    - cron: '*/1 * * * *'  # Menjalankan setiap menit

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get all folders
        id: get_folders
        run: |
          FOLDERS=$(find . -maxdepth 1 -type d ! -name '.*' ! -name 'node_modules' ! -name '.github' | sed 's|./||')
          echo "$FOLDERS" > current_folders.txt  # Simpan daftar folder saat ini
          echo "FOLDERS=$FOLDERS" >> $GITHUB_ENV

      - name: Compare with previous folders
        id: compare_folders
        run: |
          if [ -f previous_folders.txt ]; then
            PREVIOUS_FOLDERS=$(cat previous_folders.txt)
            if [ "$PREVIOUS_FOLDERS" == "$(cat current_folders.txt)" ]; then
              echo "No changes detected."
              exit 0
            fi
          fi

          # Simpan daftar folder saat ini sebagai daftar sebelumnya
          cp current_folders.txt previous_folders.txt

      - name: Read existing folders from index.html
        id: read_index
        run: |
          EXISTING_FOLDERS=$(grep -oP '(?<=<a href=")[^"]*' index.html)
          echo "EXISTING_FOLDERS=$EXISTING_FOLDERS" >> $GITHUB_ENV

      - name: Check for new folders and update index.html
        run: |
          FOLDERS="${{ env.FOLDERS }}"
          EXISTING_FOLDERS="${{ env.EXISTING_FOLDERS }}"

          if [ -z "$FOLDERS" ]; then
            echo "No folders found."
            exit 0
          fi

          FOLDER_LIST=""
          IFS=$'\n'
          for folder in $FOLDERS; do
            folder_name="${folder##*/}"
            if ! echo "$EXISTING_FOLDERS" | grep -q "^$folder$"; then
              FOLDER_LIST="$FOLDER_LIST<li><a href=\"$folder\">$folder_name</a></li>\n"
            fi
          done

          if [ -z "$FOLDER_LIST" ]; then
            echo "No new folders to add."
            exit 0
          fi

          sed -i.bak "s|<!-- FOLDER_LIST_PLACEHOLDER -->|${FOLDER_LIST}|" index.html

          if git diff --quiet; then
            echo "No changes to index.html. Skipping commit."
            exit 0
          fi

          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add index.html
          git commit -m "Add new project folders to index.html"
          git push
