      - name: Reset dan sinkronkan folder di README.md
        run: |
          if [ -z "${{ env.folders }}" ]; then
            echo "Tidak ada folder yang ditemukan di repositori."
            exit 0
          fi

          TEMPLATE_FILE="template.md"
          OUTPUT_FILE="README.md"

          > $OUTPUT_FILE
          cp $TEMPLATE_FILE $OUTPUT_FILE

          UPDATED_FOLDER_LIST=""
          for folder in ${{ env.folders }}; do
            folder_clean=$(echo "$folder" | tr '[:upper:]' '[:lower:]' | sed 's/^[ \t]*//;s/[ \t]*$//')
            UPDATED_FOLDER_LIST="$UPDATED_FOLDER_LIST- [$folder](./$folder_clean/)\n"
          done

          # Debug output untuk melihat isi daftar folder yang diperbarui
          echo "Updated Folder List: $UPDATED_FOLDER_LIST"

          sed -i.bak "s|<!-- FOLDER_LIST_PLACEHOLDER -->|$UPDATED_FOLDER_LIST|" $OUTPUT_FILE

          if git diff --quiet; then
            echo "Tidak ada perubahan pada README.md. Melewatkan commit."
            exit 0
          fi

          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add $OUTPUT_FILE
          git commit -m "Reset dan sinkronkan folder di README.md dengan repositori"
