name: Perbarui HTML dengan Folder

on:
  push:
    paths:
      - 'mini-project/**'  # Memicu workflow saat ada perubahan di folder mini-project

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositori
        uses: actions/checkout@v2

      - name: Ambil semua folder
        id: get_folders
        run: |
          # Mengambil semua folder hanya dari direktori mini-project
          FOLDERS=$(find mini-project -mindepth 1 -type d | sed 's|^mini-project/||')
          echo "Ditemukan folder: $FOLDERS"  # Debugging output
          echo "folders=$(echo "$FOLDERS" | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Cek folder saat ini di index.html
        id: read_html
        run: |
          if grep -q '<a href="' mini-project/index.html; then
            CURRENT_FOLDERS=$(grep -ioP '(?<=<a href=\").*?(?=\/\")' mini-project/index.html | tr '[:upper:]' '[:lower:]' | sort -u)
            echo "Folder saat ini di index.html: $CURRENT_FOLDERS"  # Debugging output
          else
            CURRENT_FOLDERS=""
            echo "Tidak ada folder di index.html."
          fi
          echo "current_folders=$(echo "$CURRENT_FOLDERS" | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Reset dan sinkronkan folder di index.html
        run: |
          if [ -z "${{ env.folders }}" ]; then
            echo "Tidak ada folder yang ditemukan di repositori."
            exit 0
          fi

          TEMPLATE_FILE="template.html"
          OUTPUT_FILE="mini-project/index.html"

          > $OUTPUT_FILE
          cp $TEMPLATE_FILE $OUTPUT_FILE

          UPDATED_FOLDER_LIST=""
          for folder in ${{ env.folders }}; do
            folder_clean=$(echo "$folder" | tr '[:upper:]' '[:lower:]' | sed 's/^[ \t]*//;s/[ \t]*$//')
            UPDATED_FOLDER_LIST="$UPDATED_FOLDER_LIST<li><a href=\"$folder_clean/\">$folder</a></li>\n"
          done

          echo "Mengganti placeholder di index.html"  # Debugging output
          sed -i.bak "s|<!-- FOLDER_LIST_PLACEHOLDER -->|$UPDATED_FOLDER_LIST|" $OUTPUT_FILE

          # Debugging: Tampilkan isi file setelah penggantian
          echo "Isi file setelah penggantian:"
          cat $OUTPUT_FILE

          if git diff --quiet; then
            echo "Tidak ada perubahan pada index.html. Melewatkan commit."
            exit 0
          fi

          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add $OUTPUT_FILE
          git commit -m "Reset dan sinkronkan folder di index.html dengan repositori"
          git push
