name: Detect All Folders

on:
  push:
    paths:
      - '**/'  # Mendeteksi semua perubahan di dalam folder

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate folder list
        run: |
          # Nama file HTML yang akan diperbarui
          html_file="index.html"  # Ganti dengan nama file HTML Anda

          # Membaca konten file HTML
          html_content=$(<"$html_file")

          # Mencari semua folder dan membuat list
          folder_list=""
          for dir in $(find . -type d); do
            folder_list+="<li>${dir}</li>\n"
          done

          # Mengganti placeholder dengan daftar folder
          updated_html=${html_content//<!-- FOLDER_LIST_PLACEHOLDER -->/$folder_list}

          # Menyimpan hasil ke file yang sama
          echo -e "$updated_html" > "$html_file"

      - name: Commit changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add "$html_file"
          git commit -m "Update folder list in index.html" || echo "No changes to commit"
          git push
