name: Update README with Folders

on:
  push:
    paths:
      - '**/*'  # Memicu workflow saat ada perubahan di folder manapun

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get all folders
        id: get_folders
        run: |
          # Mendapatkan semua folder kecuali .github dan node_modules, lalu menghapus trailing slash
          FOLDERS=$(ls -d */ | grep -v '\.github\|node_modules' | sed 's/\/$//')
          echo "folders=$(echo "$FOLDERS" | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Check current folders in README.md
        id: read_readme
        run: |
          # Ambil semua folder yang sudah ada di README.md
          CURRENT_FOLDERS=$(grep -ioP '(?<=<a href=\").*?(?=\/\")' README.md || echo "")
          echo "current_folders=$(echo "$CURRENT_FOLDERS" | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Sync folders in README.md
        run: |
          # Generate folder list untuk ditambahkan ke README.md
          FOLDER_LIST=""

          for folder in ${{ env.folders }}; do
            if [[ ! " ${current_folders} " =~ " ${folder} " ]]; then
              FOLDER_LIST="$FOLDER_LIST| [$folder](./$folder) |\n"
            fi
          done

          # Cek perubahan pada README.md
          if [ -n "$FOLDER_LIST" ]; then
            sed -i 's|<!-- FOLDER_LIST_PLACEHOLDER -->|'"$FOLDER_LIST"'|g' README.md
          else
            echo "No new folders to add."
            exit 0
          fi

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git pull --rebase
          git add README.md
          git commit -m "Update README.md with new folders"
          git push
