name: Perbarui HTML dengan Folder

on:
  push:
    paths:
      - '**/*'  # Memicu workflow saat ada perubahan di folder manapun

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositori
        uses: actions/checkout@v2

      - name: Ambil semua folder
        id: get_folders
        run: |
          # Mendapatkan semua folder kecuali .github dan node_modules
          FOLDERS=$(ls -d */ | grep -v '\.github\|node_modules' | sed 's/\/$//')
          echo "folders=$(echo "$FOLDERS" | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Baca template dan reset index.html
        run: |
          # Baca template dari template.html
          TEMPLATE_FILE="template.html"
          OUTPUT_FILE="index.html"

          # Salin konten template ke index.html
          cp $TEMPLATE_FILE $OUTPUT_FILE

          # Tambahkan daftar folder ke index.html
          echo "Daftar folder yang ditemukan:" 
          for folder in ${{ env.folders }}; do
            echo "Menambahkan folder: $folder"
            echo "      <li><a href=\"$folder\">$folder</a></li>" >> $OUTPUT_FILE
          done

          # Gantikan placeholder dengan daftar folder yang diperbarui
          sed -i.bak "s|<!-- FOLDER_LIST_PLACEHOLDER -->|$(cat $OUTPUT_FILE | grep -v '<ul>' | grep -v '</ul>' | grep -v '<h1>' | grep -v '<head>' | grep -v '</head>' | grep -v '<body>' | grep -v '</body>' | tr '\n' ' ' )|" $OUTPUT_FILE

          # Cek jika ada perubahan pada index.html
          if git diff --quiet; then
            echo "Tidak ada perubahan pada index.html. Melewatkan commit."
            exit 0
          fi

          # Commit dan push perubahan
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add $OUTPUT_FILE
          git commit -m "Reset dan perbarui folder di index.html"
          git push
