name: Update HTML with Folders

on:
  push:
    paths:
      - '**/*'  # Memicu workflow saat ada perubahan di folder manapun
  schedule:
    - cron: '*/5 * * * *'  # Opsional: Menjalankan setiap 5 menit (jika ada perubahan otomatis setiap interval)

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get all folders
        id: get_folders
        run: |
          # Mendapatkan semua folder kecuali .github dan node_modules, lalu menghapus trailing slash
          FOLDERS=$(ls -d */ | grep -v '\.github\|node_modules' | sed 's/\/$//')
          # Simpan folder dengan format dipisahkan spasi (untuk bisa digunakan oleh GitHub Actions)
          echo "folders=$(echo "$FOLDERS" | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Check current folders in index.html
        id: read_html
        run: |
          # Ambil semua folder yang sudah ada di index.html
          if grep -q '<a href="' index.html; then
            CURRENT_FOLDERS=$(grep -oP '(?<=<a href=\").*?(?=\/\")' index.html)
          else
            CURRENT_FOLDERS=""
          fi
          # Simpan daftar folder yang sudah ada ke dalam environment variable
          echo "current_folders=$(echo "$CURRENT_FOLDERS" | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Sync folders in index.html
        run: |
          # Jika tidak ada folder dalam repository, keluar
          if [ -z "${{ env.folders }}" ]; then
            echo "No folders found in the repository."
            exit 0
          fi

          # Generate updated folder list for HTML
          UPDATED_FOLDER_LIST=""

          # Tambahkan folder yang ada di repository tapi belum ada di index.html
          for folder in ${{ env.folders }}; do
            if [[ ! " ${current_folders} " =~ " ${folder} " ]]; then
              UPDATED_FOLDER_LIST="$UPDATED_FOLDER_LIST<li><a href=\"$folder/\">${folder}</a></li>\n"
            fi
          done

          # Cek folder yang ada di index.html tapi sudah tidak ada di repository, lalu hapus
          TEMP_INDEX_HTML=$(mktemp)
          while read -r folder; do
            if [[ " ${folders} " =~ " ${folder} " ]]; then
              # Tetap tambahkan folder yang masih ada di repository ke file baru
              echo "<li><a href=\"$folder/\">${folder}</a></li>" >> "$TEMP_INDEX_HTML"
            else
              echo "Removing folder $folder from index.html."
            fi
          done < <(grep -oP '(?<=<a href=\").*?(?=\/\")' index.html)

          # Gantikan placeholder dengan daftar folder yang diperbarui di index.html
          sed -i.bak "/<!-- FOLDER_LIST_PLACEHOLDER -->/r $TEMP_INDEX_HTML" index.html
          
          # Tambahkan folder baru yang belum ada
          if [ -n "$UPDATED_FOLDER_LIST" ]; then
            # Hapus placeholder sebelum menambahkan folder baru
            sed -i.bak "s/<!-- FOLDER_LIST_PLACEHOLDER -->/<!-- FOLDER_LIST_PLACEHOLDER -->\n$UPDATED_FOLDER_LIST/" index.html
          fi

          # Check if index.html has changed
          if git diff --quiet; then
            echo "No changes to index.html. Skipping commit."
            exit 0
          fi

          # Commit and push changes
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add index.html
          git commit -m "Sync folders in index.html with repository"
          git push
