name: Update README with folder list

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Generate folder list
        run: |
          # Find all directories in the root folder and format as markdown list
          FOLDER_LIST=$(find . -maxdepth 1 -type d ! -name '.git' | sed 's|./|- |')

          # Replace the placeholder with the generated folder list in README.md
          sed -i 's|<!-- FOLDER_LIST_PLACEHOLDER -->|'"$FOLDER_LIST"'|' README.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update folder list in README"
          git push
