      - name: Sync folders in README.md
        run: |
          # Jika tidak ada folder dalam repository, keluar
          if [ -z "${{ env.folders }}" ]; then
            echo "No folders found in the repository."
            exit 0
          fi

          # Generate updated folder list for README
          UPDATED_FOLDER_LIST=""

          # Tambahkan header tabel
          UPDATED_FOLDER_LIST="| Folder | Description |\n|--------|-------------|\n"

          # Filter nama folder yang valid dan hilangkan karakter khusus
          for folder in ${{ env.folders }}; do
            # Cek jika nama folder valid (tidak ada karakter yang bermasalah)
            if [[ "$folder" =~ ^[a-zA-Z0-9._-]+$ ]]; then
              UPDATED_FOLDER_LIST="$UPDATED_FOLDER_LIST| :file_folder: [$folder](./$folder) | Description for $folder |\n"
            else
              echo "Skipping folder $folder due to invalid name."
            fi
          done

          # Cek folder yang ada di README.md tapi sudah tidak ada di repository, lalu hapus
          TEMP_README=$(mktemp)
          while read -r folder; do
            # Cek jika folder tersebut ada di dalam repository
            if [[ " ${{ env.folders }} " =~ " ${folder} " ]]; then
              echo "| :file_folder: [$folder](./$folder) | Description for $folder |" >> "$TEMP_README"
            else
              echo "Removing folder $folder from README.md."
            fi
          done < <(grep -oP '(\w|-|_)+' README.md)

          # Gantikan placeholder dengan daftar folder yang diperbarui di README.md
          sed -i.bak "/<!-- FOLDER_LIST_PLACEHOLDER -->/r $TEMP_README" README.md
          
          # Tambahkan folder baru yang belum ada, jika ada
          if [ -n "$UPDATED_FOLDER_LIST" ]; then
            sed -i.bak "s|<!-- FOLDER_LIST_PLACEHOLDER -->|<!-- FOLDER_LIST_PLACEHOLDER -->\n$UPDATED_FOLDER_LIST|" README.md
          fi

          # Cek jika tidak ada perubahan pada README.md
          if git diff --quiet; then
            echo "No changes to README.md. Skipping commit."
            exit 0
          fi

          # Commit dan push perubahan
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Sync folders in README.md with repository"
          git push
