name: Update HTML with Folders

on:
  push:
    paths:
      - '**/*'  # Memicu workflow saat ada perubahan di folder manapun
  schedule:
    - cron: '*/1 * * * *'  # Opsional: Menjalankan setiap menit

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get all folders
        id: get_folders
        run: |
          FOLDERS=$(find . -maxdepth 1 -type d ! -name '.*' ! -name 'node_modules' ! -name '.github' | sed 's|./||')
          echo "FOLDERS=$FOLDERS" >> $GITHUB_ENV

      - name: Read existing folders from index.html
        id: read_index
        run: |
          # Ambil daftar folder yang sudah ada dari index.html
          EXISTING_FOLDERS=$(grep -oP '(?<=<a href=")[^"]*' index.html)
          echo "EXISTING_FOLDERS=$EXISTING_FOLDERS" >> $GITHUB_ENV

      - name: Check for new folders and update index.html
        run: |
          # Ambil nilai dari variabel lingkungan
          FOLDERS="${{ env.FOLDERS }}"
          EXISTING_FOLDERS="${{ env.EXISTING_FOLDERS }}"

          if [ -z "$FOLDERS" ]; then
            echo "No folders found."
            exit 0
          fi

          # Generate new folder list for HTML
          FOLDER_LIST=""
          IFS=$'\n'
          for folder in $FOLDERS; do
            folder_name="${folder##*/}"  # Ambil nama folder tanpa path
            # Cek apakah folder sudah ada
            if ! echo "$EXISTING_FOLDERS" | grep -q "^$folder$"; then
              # Jika folder baru, tambahkan ke daftar
              FOLDER_LIST="$FOLDER_LIST<li><a href=\"$folder\">$folder_name</a></li>\n"
            fi
          done

          # Jika tidak ada folder baru, keluar
          if [ -z "$FOLDER_LIST" ]; then
            echo "No new folders to add."
            exit 0
          fi

          # Replace placeholder in HTML with folder list
          sed -i.bak "s|<!-- FOLDER_LIST_PLACEHOLDER -->|${FOLDER_LIST}|" index.html

          # Check if index.html has changed
          if git diff --quiet; then
            echo "No changes to index.html. Skipping commit."
            exit 0
          fi

          # If changes exist, commit and push the update
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add index.html
          git commit -m "Add new project folders to index.html"
          git push
