name: Perbarui README

on:
  push:
    paths:
      - '**/*'  # Memicu workflow saat ada perubahan di folder manapun

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositori
        uses: actions/checkout@v2

      - name: Ambil semua folder
        id: get_folders
        run: |
          # Mendapatkan semua folder kecuali .github dan node_modules
          FOLDERS=$(ls -d */ | grep -v '\.github\|node_modules' | sed 's/\/$//')
          echo "folders=$(echo "$FOLDERS" | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Reset dan sinkronkan daftar folder di README.md
        run: |
          # Jika tidak ada folder dalam repositori, keluar
          if [ -z "${{ env.folders }}" ]; then
            echo "Tidak ada folder yang ditemukan di repositori."
            exit 0
          fi

          # Baca template dari template.md
          TEMPLATE_FILE="template.md"
          OUTPUT_README="README.md"

          # Hapus isi file README.md
          > $OUTPUT_README

          # Salin konten template ke file README.md
          cp $TEMPLATE_FILE $OUTPUT_README

          # Generate daftar folder untuk README.md
          UPDATED_FOLDER_LIST=""

          # Tambahkan folder yang ada ke list
          for folder in ${{ env.folders }}; do
            folder_clean=$(echo "$folder" | tr '[:upper:]' '[:lower:]' | sed 's/^[ \t]*//;s/[ \t]*$//')  # Normalisasi nama folder
            UPDATED_FOLDER_LIST="$UPDATED_FOLDER_LIST- 📁 [$folder](./$folder_clean)\n"
          done

          # Gantikan placeholder dengan daftar folder yang diperbarui di README.md
          sed -i.bak "s|<!-- FOLDER_LIST_PLACEHOLDER -->|$UPDATED_FOLDER_LIST|" $OUTPUT_README

          # Cek jika tidak ada perubahan pada README.md
          if git diff --quiet; then
            echo "Tidak ada perubahan pada README.md. Melewatkan commit."
            exit 0
          fi

          # Commit dan push perubahan
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add $OUTPUT_README
          git commit -m "
