name: Perbarui README dengan Daftar Folder dan Ikon

on:
  push:
    paths:
      - '**/*'  # Memicu workflow saat ada perubahan di folder manapun

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositori
        uses: actions/checkout@v2

      - name: Ambil semua folder
        id: get_folders
        run: |
          # Mendapatkan semua folder kecuali .github dan node_modules
          FOLDERS=$(ls -d */ | grep -v '\.github\|node_modules' | sed 's/\/$//')
          echo "folders=$(echo "$FOLDERS" | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Reset dan perbarui README.md
        run: |
          README_FILE="README.md"
          TEMPLATE_FILE="template.md"

          # Buat ulang konten README.md berdasarkan template.md
          cp $TEMPLATE_FILE $README_FILE

          # Menentukan ikon untuk setiap folder (gunakan emoji atau ikon dari Font Awesome)
          ICON="📂"  # Gunakan emoji default

          # Generate daftar folder untuk README.md
          UPDATED_FOLDER_LIST=""

          for folder in ${{ env.folders }}; do
            UPDATED_FOLDER_LIST="$UPDATED_FOLDER_LIST| $ICON $folder | Deskripsi folder $folder |\n"
          done

          # Gantikan placeholder dengan daftar folder yang diperbarui di README.md
          sed -i.bak "s|<!-- FOLDER_LIST_PLACEHOLDER -->|$UPDATED_FOLDER_LIST|" $README_FILE

          # Cek jika tidak ada perubahan pada README.md
          if git diff --quiet; then
            echo "Tidak ada perubahan pada README.md. Melewatkan commit."
            exit 0
          fi

          # Commit dan push perubahan
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add $README_FILE
          git commit -m "Perbarui README.md dengan daftar folder dan ikon"
          git push
