name: Perbarui HTML dengan Folder

on:
  push:
    paths:
      - '**/*'  # Memicu workflow saat ada perubahan di folder manapun

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositori
        uses: actions/checkout@v2

      - name: Ambil semua folder
        id: get_folders
        run: |
          # Mendapatkan semua folder kecuali .github dan node_modules, lalu menghapus trailing slash
          FOLDERS=$(ls -d */ | grep -v '\.github\|node_modules' | sed 's/\/$//')
          echo "folders=$(echo "$FOLDERS" | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Cek folder saat ini di index.html
        id: read_html
        run: |
          # Ambil semua folder yang sudah ada di index.html secara case-insensitive
          if grep -q '<a href="' index.html; then
            CURRENT_FOLDERS=$(grep -ioP '(?<=<a href=\").*?(?=\/\")' index.html | tr '[:upper:]' '[:lower:]')
          else
            CURRENT_FOLDERS=""
          fi
          echo "current_folders=$(echo "$CURRENT_FOLDERS" | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Sinkronkan folder di index.html
        run: |
          # Jika tidak ada folder dalam repositori, keluar
          if [ -z "${{ env.folders }}" ]; then
            echo "Tidak ada folder yang ditemukan di repositori."
            exit 0
          fi

          # Hasilkan daftar folder yang diperbarui untuk HTML
          UPDATED_FOLDER_LIST=""
          declare -A existing_folders  # Menggunakan associative array untuk menghindari duplikasi

          # Tambahkan folder yang ada di repositori tapi belum ada di index.html (case-insensitive)
          for folder in ${{ env.folders }}; do
            folder_lower=$(echo "$folder" | tr '[:upper:]' '[:lower:]')
            existing_folders["$folder_lower"]=1  # Simpan dalam associative array

            if [[ ! " ${current_folders} " =~ " ${folder_lower} " ]]; then
              UPDATED_FOLDER_LIST="$UPDATED_FOLDER_LIST<li><a href=\"$folder/\">${folder}</a></li>\n"
            fi
          done

          # Hapus folder yang tidak ada di repositori dari index.html
          TEMP_INDEX_HTML=$(mktemp)

          # Loop untuk mengecek dan hanya menyimpan folder yang masih ada
          while read -r folder; do
            folder_lower=$(echo "$folder" | tr '[:upper:]' '[:lower:]')
            if [[ "${existing_folders[$folder_lower]}" ]]; then
              echo "<li><a href=\"$folder/\">${folder}</a></li>" >> "$TEMP_INDEX_HTML"
            else
              echo "Menghapus folder $folder dari index.html."
            fi
          done < <(grep -ioP '(?<=<a href=\").*?(?=\/\")' index.html)

          # Gantikan placeholder dengan daftar folder yang diperbarui di index.html
          sed -i.bak "/<!-- FOLDER_LIST_PLACEHOLDER -->/r $TEMP_INDEX_HTML" index.html
          
          # Tambahkan folder baru yang belum ada, jika ada
          if [ -n "$UPDATED_FOLDER_LIST" ]; then
            sed -i.bak "s|<!-- FOLDER_LIST_PLACEHOLDER -->|<!-- FOLDER_LIST_PLACEHOLDER -->\n$UPDATED_FOLDER_LIST|" index.html
          fi

          # Cek jika tidak ada perubahan pada index.html
          if git diff --quiet; then
            echo "Tidak ada perubahan pada index.html. Melewatkan commit."
            exit 0
          fi

          # Commit dan push perubahan
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add index.html
          git commit -m "Sinkronkan folder di index.html dengan repositori"
          git push
