name: Perbarui HTML dengan Folder

on:
  push:
    paths:
      - '**/*'  # Memicu workflow saat ada perubahan di folder manapun
  schedule:
    - cron: '*/5 * * * *'  # Opsional: Menjalankan setiap 5 menit

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Dapatkan semua folder
        id: get_folders
        run: |
          # Mendapatkan semua folder kecuali .github dan node_modules, lalu menghapus trailing slash
          FOLDERS=$(ls -d */ | grep -v '\.github\|node_modules' | sed 's/\/$//')
          echo "folders=$(echo "$FOLDERS" | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Periksa folder saat ini di index.html
        id: read_html
        run: |
          # Ambil semua folder yang sudah ada di index.html
          if grep -q '<a href="' index.html; then
            CURRENT_FOLDERS=$(grep -oP '(?<=<a href=\").*?(?=\/\")' index.html)
          else
            CURRENT_FOLDERS=""
          fi
          echo "current_folders=$(echo "$CURRENT_FOLDERS" | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Sinkronisasi folder di index.html
        run: |
          # Jika tidak ada folder dalam repository, keluar
          if [ -z "${{ env.folders }}" ]; then
            echo "Tidak ada folder ditemukan dalam repository."
            exit 0
          fi

          # Periksa folder baru yang akan ditambahkan
          UPDATED_FOLDER_LIST=""
          for folder in ${{ env.folders }}; do
            if [[ ! " ${current_folders} " =~ " ${folder} " ]]; then
              UPDATED_FOLDER_LIST="$UPDATED_FOLDER_LIST<li><a href=\"$folder/\">${folder}</a></li>\n"
            fi
          done

          # Jika tidak ada folder baru yang perlu ditambahkan, keluar
          if [ -z "$UPDATED_FOLDER_LIST" ]; then
            echo "Tidak ada folder baru yang perlu ditambahkan ke index.html. Keluar."
            exit 0
          fi

          # File sementara untuk daftar folder di index.html saat ini
          TEMP_INDEX_HTML=$(mktemp)
          while read -r folder; do
            if [[ " ${folders} " =~ " ${folder} " ]]; then
              echo "<li><a href=\"$folder/\">${folder}</a></li>" >> "$TEMP_INDEX_HTML"
            else
              echo "Menghapus folder $folder dari index.html."
            fi
          done < <(grep -oP '(?<=<a href=\").*?(?=\/\")' index.html)

          # Gantikan placeholder dengan daftar folder yang diperbarui di index.html
          sed -i.bak "/<!-- FOLDER_LIST_PLACEHOLDER -->/r $TEMP_INDEX_HTML" index.html
          
          # Tambahkan folder baru jika ada
          sed -i.bak "s|<!-- FOLDER_LIST_PLACEHOLDER -->|<!-- FOLDER_LIST_PLACEHOLDER -->\n$UPDATED_FOLDER_LIST|" index.html

          # Cek jika tidak ada perubahan pada index.html
          if git diff --quiet; then
            echo "Tidak ada perubahan pada index.html. Melewati commit."
            exit 0
          fi

          # Commit d
