name: Update HTML with Folders

on:
  push:
    paths:
      - '**/*'  # Memicu workflow saat ada perubahan di folder manapun

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get all folders
        id: get_folders
        run: |
          # Mendapatkan semua folder kecuali .github dan node_modules, lalu menghapus trailing slash
          FOLDERS=$(ls -d */ | grep -v '\.github\|node_modules' | sed 's/\/$//')
          echo "folders=$(echo "$FOLDERS" | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Check current folders in index.html
        id: read_html
        run: |
          # Ambil semua folder yang sudah ada di index.html, case-insensitive
          if grep -q '<a href="' index.html; then
            CURRENT_FOLDERS=$(grep -ioP '(?<=<a href=\").*?(?=\/\")' index.html | tr '[:upper:]' '[:lower:]')
          else
            CURRENT_FOLDERS=""
          fi
          echo "current_folders=$(echo "$CURRENT_FOLDERS" | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Sync folders in index.html
        run: |
          # Jika tidak ada folder dalam repository, keluar
          if [ -z "${{ env.folders }}" ]; then
            echo "No folders found in the repository."
            exit 0
          fi

          # Generate updated folder list for HTML
          UPDATED_FOLDER_LIST=""

          # Tambahkan folder yang ada di repository tapi belum ada di index.html (case-insensitive)
          for folder in ${{ env.folders }}; do
            folder_lower=$(echo "$folder" | tr '[:upper:]' '[:lower:]')
            if [[ ! " ${CURRENT_FOLDERS} " =~ " ${folder_lower} " ]]; then
              UPDATED_FOLDER_LIST="$UPDATED_FOLDER_LIST<li><a href=\"$folder/\">${folder}</a></li>\n"
            fi
          done

          # Hapus folder yang tidak ada di repository dari index.html
          TEMP_INDEX_HTML=$(mktemp)

          # Baca folder dari index.html dan hapus yang tidak ada di repository
          while read -r folder; do
            folder_lower=$(echo "$folder" | tr '[:upper:]' '[:lower:]')
            if [[ " ${{ env.folders }} " =~ " ${folder_lower} " ]]; then
              echo "<li><a href=\"$folder/\">${folder}</a></li>" >> "$TEMP_INDEX_HTML"
            else
              echo "Menghapus folder $folder dari index.html."
            fi
          done < <(grep -ioP '(?<=<a href=\").*?(?=\/\")' index.html)

          # Hapus semua instance dari placeholder sebelum menambahkan yang baru
          sed -i.bak "/<!-- FOLDER_LIST_PLACEHOLDER -->/d" index.html

          # Gabungkan konten dan tambahkan ke index.html
          if [ -n "$UPDATED_FOLDER_LIST" ]; then
            echo -e "$UPDATED_FOLDER_LIST\n<!-- FOLDER_LIST_PLACEHOLDER -->" >> index.html
          else
            echo "<!-- FOLDER_LIST_PLACEHOLDER -->" >> index.html
          fi

          # Cek jika tidak ada perubahan pada index.html
          if git diff --quiet; then
            echo "No changes to index.html. Skipping commit."
            exit 0
          fi

          # Commit dan push perubahan
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add index.html
          git commit -m "Sync folders in index.html with repository"
          git push
