name: Perbarui HTML dengan Folder

on:
  push:
    paths:
      - '**/*'  # Memicu workflow saat ada perubahan di folder manapun

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositori
        uses: actions/checkout@v2

      - name: Ambil semua folder
        id: get_folders
        run: |
          # Mendapatkan semua folder kecuali .github dan node_modules
          FOLDERS=$(ls -d */ | grep -v '\.github\|node_modules' | sed 's/\/$//')
          echo "folders=$(echo "$FOLDERS" | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Cek folder saat ini di index.html
        id: read_html
        run: |
          # Ambil semua folder yang sudah ada di index.html secara case-insensitive
          if grep -q '<a href="' index.html; then
            CURRENT_FOLDERS=$(grep -ioP '(?<=<a href=\").*?(?=\/\")' index.html | tr '[:upper:]' '[:lower:]' | sort -u)
          else
            CURRENT_FOLDERS=""
          fi
          echo "current_folders=$(echo "$CURRENT_FOLDERS" | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Reset dan sinkronkan folder di index.html
        run: |
          # Jika tidak ada folder dalam repositori, keluar
          if [ -z "${{ env.folders }}" ]; then
            echo "Tidak ada folder yang ditemukan di repositori."
            exit 0
          fi

          # Template baru untuk index.html
          echo '<!DOCTYPE html>' > index.html
          echo '<html lang="en">' >> index.html
          echo '  <head>' >> index.html
          echo '    <meta charset="UTF-8">' >> index.html
          echo '    <meta name="viewport" content="width=device-width, initial-scale=1.0">' >> index.html
          echo '    <title>Project Folder List</title>' >> index.html
          echo '  </head>' >> index.html
          echo '  <body>' >> index.html
          echo '    <h1>Project Folders</h1>' >> index.html
          echo '    <ul>' >> index.html

          # Tambahkan folder yang ada ke index.html
          for folder in ${{ env.folders }}; do
            folder_clean=$(echo "$folder" | tr '[:upper:]' '[:lower:]' | sed 's/^[ \t]*//;s/[ \t]*$//')  # Normalisasi nama folder
            echo "      <li><a href=\"$folder_clean/\">$folder</a></li>" >> index.html
          done

          echo '    </ul>' >> index.html
          echo '  </body>' >> index.html
          echo '</html>' >> index.html

          # Cek jika tidak ada perubahan pada index.html
          if git diff --quiet; then
            echo "Tidak ada perubahan pada index.html. Melewatkan commit."
            exit 0
          fi

          # Commit dan push perubahan
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add index.html
          git commit -m "Reset dan sinkronkan folder di index.html dengan repositori"
          git push
